---    
  - name: 'Upgrade all packages to the latest version'
    apt:
      name: "*"
      state: latest
    become: true

  - name: 'Install python pip'
    apt:
      name: python3-pip
      state: present
    become: true

  - name: 'Install pwgen'
    apt:
      name: pwgen
      state: present
    become: true
